// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "jquery"
import "jquery_ujs"
import "bootstrap"
import "@popperjs/core"
import "@hotwired/turbo-rails"
import "controllers"
import "prompts"
import "categories"
import "@fortawesome/fontawesome-free"